In [ ]:
import os
import numpy as np
from tensorflow.keras.preprocessing import image
from sklearn.preprocessing import LabelEncoder

from keras.models import Sequential
from keras import layers
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
train_path = "/content/drive/MyDrive/BTC Dataset-20221029T063940Z-001/BTC Dataset/Training/"

classes = os.listdir(train_path)

In [ ]:
classes

['meningioma_tumor', 'pituitary_tumor', 'no_tumor', 'glioma_tumor']

In [ ]:
img_data = []
img_labels = []

count = 1

for cls in classes:
  imgs = os.listdir(train_path + cls)

  for i in imgs:
    img_path = train_path + cls + "/" + i
    print(img_path)

    img = image.load_img(img_path,target_size=(224,224,3))
    img = image.img_to_array(img)
    
    img_data.append(img)
    img_labels.append(cls)
    print("\n\n", count, "\n\n")
    count = count + 1

Streaming output truncated to the last 5000 lines.


/content/drive/MyDrive/BTC Dataset-20221029T063940Z-001/BTC Dataset/Training/glioma_tumor/gg (192).jpg


 2068 


/content/drive/MyDrive/BTC Dataset-20221029T063940Z-001/BTC Dataset/Training/glioma_tumor/gg (513).jpg


 2069 


/content/drive/MyDrive/BTC Dataset-20221029T063940Z-001/BTC Dataset/Training/glioma_tumor/gg (585).jpg


 2070 


/content/drive/MyDrive/BTC Dataset-20221029T063940Z-001/BTC Dataset/Training/glioma_tumor/gg (369).jpg


 2071 


/content/drive/MyDrive/BTC Dataset-20221029T063940Z-001/BTC Dataset/Training/glioma_tumor/gg (304).jpg


 2072 


/content/drive/MyDrive/BTC Dataset-20221029T063940Z-001/BTC Dataset/Training/glioma_tumor/gg (217).jpg


 2073 


/content/drive/MyDrive/BTC Dataset-20221029T063940Z-001/BTC Dataset/Training/glioma_tumor/gg (575) (1).jpg


 2074 


/content/drive/MyDrive/BTC Dataset-20221029T063940Z-001/BTC Dataset/Training/glioma_tumor/gg (333).jpg


 2075 


/content/drive/MyDrive/BTC Data

In [ ]:
X = np.asarray(img_data)
y = np.asarray(img_labels)

In [ ]:
X.shape, y.shape

((2900, 224, 224, 3), (2900,))

In [ ]:
# Converting Strings to Integers

le = LabelEncoder()
Y = le.fit_transform(y)

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=42)

In [ ]:
model = Sequential()
model.add(layers.Conv2D(16, 3, activation = 'relu', input_shape = (224, 224, 3)))
model.add(layers.MaxPooling2D())

model.add(layers.Conv2D(32, 3, activation = 'relu'))
model.add(layers.MaxPooling2D())

model.add(layers.Conv2D(32, 3, activation = 'relu'))
model.add(layers.MaxPooling2D())

model.add(layers.Conv2D(64, 3, activation = 'relu'))
model.add(layers.MaxPooling2D()) 

model.add(layers.Flatten())

model.add(layers.Dense(128,activation = 'relu'))
model.add(layers.Dense(4, activation = 'softmax'))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 222, 222, 16)      448       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 111, 111, 16)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 109, 109, 32)      4640      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 54, 54, 32)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 52, 52, 32)        9248      
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 26, 26, 32)      

In [ ]:
model.compile(loss = 'sparse_categorical_crossentropy', optimizer = "adam", metrics = ["accuracy"])

In [ ]:
model.fit(X_train,y_train,epochs=10, batch_size=32,validation_data=(X_test,y_test))

Epoch 1/10
73/73 [==============================] - 102s 1s/step - loss: 8.6952 - accuracy: 0.5634 - val_loss: 0.7316 - val_accuracy: 0.6966
Epoch 2/10
73/73 [==============================] - 98s 1s/step - loss: 0.5385 - accuracy: 0.7819 - val_loss: 0.5656 - val_accuracy: 0.7845
Epoch 3/10
73/73 [==============================] - 97s 1s/step - loss: 0.3605 - accuracy: 0.8707 - val_loss: 0.5863 - val_accuracy: 0.7914
Epoch 4/10
73/73 [==============================] - 99s 1s/step - loss: 0.2268 - accuracy: 0.9185 - val_loss: 0.4890 - val_accuracy: 0.8466
Epoch 5/10
73/73 [==============================] - 99s 1s/step - loss: 0.1459 - accuracy: 0.9504 - val_loss: 0.4514 - val_accuracy: 0.8655
Epoch 6/10
73/73 [==============================] - 97s 1s/step - loss: 0.1240 - accuracy: 0.9543 - val_loss: 0.5151 - val_accuracy: 0.8293
Epoch 7/10
73/73 [==============================] - 98s 1s/step - loss: 0.0979 - accuracy: 0.9677 - val_loss: 0.4387 - val_accuracy: 0.8707
Epoch 8/10
73/73 [=

In [ ]:
y_pred = np.argmax(model.predict(X_test),axis=-1)

19/19 [==============================] - 6s 332ms/step


In [ ]:
accuracy_score(y_test, y_pred)

0.8603448275862069

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.88      0.88       161
           1       0.80      0.81      0.81       176
           2       0.80      0.84      0.82        82
           3       0.94      0.90      0.92       161

    accuracy                           0.86       580
   macro avg       0.86      0.86      0.86       580
weighted avg       0.86      0.86      0.86       580



In [ ]:
print(confusion_matrix(y_test, y_pred))

[[142  15   3   1]
 [ 13 143  12   8]
 [  1  11  69   1]
 [  4  10   2 145]]


In [ ]:
# https://colab.research.google.com/drive/1nuhslTY_0qlZ-O4WIsYx3fgsZKCbrS4H#scrollTo=Yy8KJD8bud6x